### ISSUE TITLE
Add stop application endpoint to REST API

### ISSUE THREAD

**Issue by simonfontana** [Ericsson/ecchronos#181]
It should be possible to stop ecChronos from the REST API. This can be useful for example in a restore scenario where you want to make sure the that scheduling is refreshed after the restore.

**Comment by itskarlsson** [comment]
This is already supported by configuring the Springboot actuator.

It has to be enabled in application.yml as follows:
```
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown # if you wish to expose it through rest. Default it is only exposed through JMX due to security reasons.
```
Once enabled, it can be used like this:
```
curl -X POST 'http://localhost:8080/actuator/shutdown'
{"message":"Shutting down, bye..."}
```
