### ISSUE TITLE
Move exclusion of metrics to specific reporters

### ISSUE THREAD

**Issue by masokol** [Ericsson/ecchronos#411]
We should move exclusion of metrics to specific reporters so it's possible to have different metrics exposed for different reporters.
i.e move this

```
  ##
  ## The metrics can be excluded using quoted regular expressions.
  ## By default, no metrics are excluded.
  ## For list of available metrics refer to the documentation.
  ##
  excluded: []
```

to

```
  ##
  ## Decides how statistics should be exposed.
  ## If all reporting is disabled, the statistics will be disabled as well.
  ##
  reporting:
    jmx:
      enabled: true
    file:
      enabled: true
    http:
      enabled: true
```
