### ISSUE TITLE
Exclude metrics based on tags

### ISSUE THREAD

**Issue by masokol** [Ericsson/ecchronos#446]
Ecchronos should have support to exclude metrics on tags as well.
Currently only exlusion by metric name is supported but this is not enough.

I'm thinking something like this:

```
excludedMetrics:
  - name: <metric name or regexp>
    tags:
      keyspace: "<keyspace or regexp>"
      table: "<table or regexp>"
```

For example given this, all metrics should be excluded:

```
excludedMetrics:
  - name: .*
```

Given this, all metrics with tag keyspace=testkeyspace should be excluded
```
excludedMetrics:
  - name: .*
    tags:
      keyspace: testkeyspace
```

GIven this, all metrics for keyspace testkeyspace and table testtable should be excluded

```
excludedMetrics:
  - name: .*
    tags:
      keyspace: testkeyspace
      table: testtable
```
