### ISSUE TITLE
SETUP.md wrong parameters used for CQL security

### ISSUE THREAD

**Issue by masokol** [Ericsson/ecchronos#471]
The [SETUP.md](https://github.com/Ericsson/ecchronos/blob/master/docs/SETUP.md) about using PEM certificates for CQL is wrong.

Specifically these 2 params are wrong **certificate_key** and **certificate_authorities**.

This is what's documented
```
cql:
  credentials:
    enabled: true
    username: cassandra
    password: cassandra
  tls:
    enabled: false
    certificate: /path/to/certificate
    certificate_key: /path/to/certificate_key
    certificate_authorities: /path/to/certificate_authorities
    protocol: TLSv1.2,TLSv1.3
    cipher_suites:
    require_endpoint_verification: false
```

It should be:

```
cql:
  credentials:
    enabled: true
    username: cassandra
    password: cassandra
  tls:
    enabled: false
    certificate: /path/to/certificate
    certificate_private_key: /path/to/certificate_key
    trust_certificate: /path/to/certificate_authorities
    protocol: TLSv1.2,TLSv1.3
    cipher_suites:
    require_endpoint_verification: false
```
