### ISSUE TITLE
Make failed job backoff time configurable

### ISSUE THREAD

**Issue by masokol** [Ericsson/ecchronos#475]
Right now when a scheduled job fails there's a [backoff of 30 minutes](https://github.com/Ericsson/ecchronos/blob/master/core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/scheduling/ScheduledJob.java#L28) before the job is attempted again. It would be nice to have this configurable in ecc.yaml.

Something like this maybe:

```
scheduler:
  backoff:
    time: 30
    unit: MINUTES
```

If it's not configured we should default to the old value i.e 30 minutes.
