### ISSUE TITLE
Create JMXAgentConfig to add Hosts in JMX Session Through ecc.yml

### ISSUE THREAD

**Issue by VictorCavichioli** [Ericsson/ecchronos#675]
Story Description:
Create new object in package com.ericsson.bss.cassandra.ecchronos.application.config.connection called DatacenterAwareConfig(_**If it not exists**_), it must represent the below configuration in ecc.yml:

```yaml
jmx:
    datacenterAware:
      enabled: false
      datacenters:
      - name: datacenter1
        hosts:
        - host: 127.0.0.1
          port: 7100
        - host: 127.0.0.2
          port: 7200
        - host: 127.0.0.3
          port: 7300
        - host: 127.0.0.4
          port: 7400
```

connection.jmx.datacenterAware.enabled must be false by default to avoid breaking the sidecar functionality; these described hosts will be added in the JmxConnection on the application startup; in the a future task we'll create a new JmxConnectionProvider specific for the agent, which will be activated by the connection.jmx.datacenterAware.enabled=true and connection.jmx.provider=DatacenterJMXConnectionProvider.java, so to avoid future problems, expose the DatacenterAwareConfig in the JmxConnection.java class.

Acceptance Criteria:

- [x] DatacenterAwareConfig Designed as Described;
- [x] New TestConfig class created to specific Agent tests, also is proposed to change the old name of TestConfig to TestDefaultConfig or TestSidecarConfig;
- [ ] Architecture documentation updated with new topics.

Definition of Done:

Code tested and approved by maintainers.

Notes:

Related to #652

**Comment by VictorCavichioli** [comment]
After some discussions we decided to change the configuration shape for the new below:

```yaml
agent:
      enabled: false
      type: datacenterAware
      contactPoints:
      - host: 127.0.0.1
        port: 9042
      - host: 127.0.0.2
        port: 9042
      datacenterAware:
        datacenters:
        - name: datacenter1
      rackAware:
        racks:
        - datacenterName: datacenter1
          rackName: rack1
      hostAware:
        hosts:
          - host: 127.0.0.1
            port: 9042
          - host: 127.0.0.2
            port: 9042
          - host: 127.0.0.3
            port: 9042
          - host: 127.0.0.4
            port: 9042
```
