### ISSUE TITLE
Create RepairConfiguration class for repair configurations

### ISSUE THREAD

**Issue by VictorCavichioli** [Ericsson/ecchronos#716]
Story Description:
To allow repair operations to be performed in a parameterized and consistent way, we need to encapsulate all repair configuration properties in a single class. This will simplify the management of operations and allow adjustments and optimizations to be made centrally, without the need to modify multiple points in the code. Additionally, this class will provide flexibility to add new configuration parameters in the future.

The propose is to create two classes, one to map the instructions from ecc.yaml in the application module and another in the core module to receive this information and pass for the repair jobs

Acceptance Criteria:

_[Acceptance Criterion 1]: Code designed as described._

_[Acceptance Criterion 2]: unit-tests done._

Definition of Done:

Code approved by maintainers

Notes:

This is how it should looks like on the ecc.yaml:

```yaml
repair:
  interval:
    time: 7
    unit: days
  initial_delay:
    time: 1
    unit: days
  priority:
    granularity_unit: HOURS
  unwind_ratio: 0.0
  backoff:
    time: 30
    unit: MINUTES
  repair_type: incremental
```
